const params=new URLSearchParams(location.search);const LANG=(params.get('lang')||document.documentElement.lang||'cs').toLowerCase();
const D={
 cs:{back:'Zpět do katalogu',gallery:'Galerie',specs:'Charakteristiky',equipment:'Výbava',request:'Poptat automobil',missing:'Údaje připravujeme.',equipmentMissing:'Kompletní výbava bude doplněna.',name:'Jméno / Name',phone:'Telefon / WhatsApp',message:'Zpráva',send:'ODESLAT ZPRÁVU',priceAsk:'Cena na dotaz',km:'km'},
 en:{back:'Back to inventory',gallery:'Gallery',specs:'Specifications',equipment:'Equipment',request:'Request this vehicle',missing:'Details are being prepared.',equipmentMissing:'Full equipment details will be added.',name:'Name',phone:'Phone / WhatsApp',message:'Message',send:'SEND MESSAGE',priceAsk:'Price on request',km:'km'},
 de:{back:'Zurück zum Katalog',gallery:'Galerie',specs:'Fahrzeugdaten',equipment:'Ausstattung',request:'Fahrzeug anfragen',missing:'Die Angaben werden vorbereitet.',equipmentMissing:'Die vollständige Ausstattung wird ergänzt.',name:'Name',phone:'Telefon / WhatsApp',message:'Nachricht',send:'NACHRICHT SENDEN',priceAsk:'Preis auf Anfrage',km:'km'},
 ru:{back:'Назад в каталог',gallery:'Галерея',specs:'Характеристики',equipment:'Комплектация',request:'Запросить автомобиль',missing:'Данные подготавливаются.',equipmentMissing:'Полная комплектация будет добавлена.',name:'Имя',phone:'Телефон / WhatsApp',message:'Сообщение',send:'ОТПРАВИТЬ СООБЩЕНИЕ',priceAsk:'Цена по запросу',km:'км'}
}[LANG]||null;
const indexByLang={cs:'index.html',en:'index_en.html',de:'index_de.html',ru:'index_ru.html'};
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function num(v){const s=String(v||'').replace(/[^\d]/g,'');return s?Number(s):0}
function euro(v){const n=num(v);return n?n.toLocaleString(LANG==='de'?'de-DE':LANG==='en'?'en-GB':LANG==='ru'?'ru-RU':'cs-CZ')+' €':D.priceAsk}
function km(v){const n=num(v);return n?n.toLocaleString(LANG==='de'?'de-DE':LANG==='en'?'en-GB':LANG==='ru'?'ru-RU':'cs-CZ')+' '+D.km:''}
function val(c,ks){for(const k of ks){if(c[k]&&String(c[k]).trim())return c[k]}return ''}
function spec(a,b){return b?`<div class="detail-spec"><span>${a}</span><b>${b}</b></div>`:''}
function loadDetail(){
 document.documentElement.lang=LANG;const id=params.get('car');const cars=window.CARS_DATA||[];const c=cars.find(x=>x.slug===id)||cars[0];const root=document.getElementById('carDetail');if(!c||!root)return;
 const title=((val(c,['Марка'])+' '+val(c,['Модель'])).trim())||'Automobil';const img=val(c,['Фото']);const imgTag=img?`<img src="assets/cars/${esc(img)}" alt="${esc(title)}">`:'';
 const labels=LANG==='ru'?['Год','Пробег','Двигатель','Топливо','Коробка','Цвет','VIN']:LANG==='de'?['Jahr','Kilometerstand','Motor','Kraftstoff','Getriebe','Farbe','VIN']:LANG==='en'?['Year','Mileage','Engine','Fuel','Gearbox','Colour','VIN']:['Rok','Nájezd','Motor','Palivo','Převodovka','Barva','VIN'];
 const specs=[spec(labels[0],esc(val(c,['Год']))),spec(labels[1],km(val(c,['Пробег']))),spec(labels[2],esc(val(c,['Двигатель']))),spec(labels[3],esc(val(c,['Топливо']))),spec(labels[4],esc(val(c,['Коробка']))),spec(labels[5],esc(val(c,['Цвет']))),spec(labels[6],esc(val(c,['VIN'])))].join('');
 root.innerHTML=`<section class="detail-hero"><div><a class="back-link" href="${indexByLang[LANG]||'index.html'}#catalog">← ${D.back}</a><div class="kicker">LUXES EXECUTIVE</div><h1>${esc(title)}</h1><p class="lead">${esc(val(c,['Комплектация'])||D.equipmentMissing)}</p><div class="detail-price">${euro(val(c,['Цена (€)']))}</div><a class="btn btn-black" href="#request">${D.request}</a></div><div class="detail-main-photo">${imgTag}</div></section><section class="section"><div class="detail-layout"><div><h2>${D.gallery}</h2><div class="gallery-grid">${imgTag}${imgTag}${imgTag}${imgTag}</div></div><div><h2>${D.specs}</h2><div class="detail-specs">${specs||'<p>'+D.missing+'</p>'}</div><h2>${D.equipment}</h2><p class="detail-text">${esc(val(c,['Комплектация'])||D.equipmentMissing)}</p></div></div></section><section class="contact-section" id="request"><div class="contact-wrap"><h2>${D.request}</h2><div class="contact-card"><form class="contact-form"><div class="form-row"><input placeholder="${D.name}"><input placeholder="${D.phone}"></div><div class="form-row"><input placeholder="E-mail"><input value="${esc(title)}"></div><textarea placeholder="${D.message}"></textarea><button class="submit" type="button">${D.send}</button></form><div class="contact-info"><div class="contact-line">+420 777 399 799</div><div class="contact-line">executive@luxes.cz</div><div class="contact-line">WhatsApp</div></div></div></div></section>`;
}
loadDetail();