
const CSV_FILE='cars.csv';
function parseCSV(text){const rows=[];let row=[],field='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c=='"'&&q&&n=='"'){field+='"';i++;}else if(c=='"')q=!q;else if((c==';'||c==',')&&!q){row.push(field.trim());field='';}else if((c=='\n'||c=='\r')&&!q){if(field||row.length){row.push(field.trim());rows.push(row);row=[];field='';}if(c=='\r'&&n=='\n')i++;}else field+=c;}if(field||row.length){row.push(field.trim());rows.push(row);}return rows.filter(r=>r.some(v=>String(v).trim()!==''));}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function n(v){const x=String(v||'').replace(/[^\d]/g,'');return x?Number(x):0}
function euro(v){const x=n(v);return x?x.toLocaleString('cs-CZ')+' €':'Cena na dotaz'}
function km(v){const x=n(v);return x?x.toLocaleString('cs-CZ')+' km':''}
function isTop(v){return String(v||'').trim().toUpperCase()==='ANO'}
function card(c){const title=`${esc(c['Марка'])} ${esc(c['Модель'])}`.trim()||'Automobil';const img=c['Фото']?`assets/cars/${esc(c['Фото'])}`:'';const top=isTop(c['TOP']||c['⭐ TOP']);return `<article class="card"><div class="card-photo">${img?`<img src="${img}" alt="${title}" onerror="this.remove();">`:'Foto'}<span class="status">${esc(c['Статус']||'V prodeji')}</span>${top?'<span class="top">TOP</span>':''}</div><div class="card-body"><div class="card-title">${title}</div><div class="card-version">${esc(c['Комплектация']||'')}</div><div class="meta"><span>${esc(c['Год']||'')}</span><span>${km(c['Пробег'])}</span><span>${esc(c['Двигатель']||'')}</span><span>${esc(c['Коробка']||'')}</span><span>${esc(c['Топливо']||'')}</span><span>${esc(c['Цвет']||'')}</span></div><div class="price">${euro(c['Цена (€)'])}</div><a class="detail" href="#contact">Detail</a></div></article>`}
async function loadCars(){const grid=document.querySelector('#catalogGrid');if(!grid)return;try{const res=await fetch(CSV_FILE+'?v='+Date.now());const text=await res.text();const rows=parseCSV(text);const h=rows.shift()||[];const cars=rows.map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]||'']))).filter(c=>c['Фото']||c['Марка']||c['Модель']).sort((a,b)=>(isTop(a['TOP'])?0:1)-(isTop(b['TOP'])?0:1)||((Number(a['Порядок'])||9999)-(Number(b['Порядок'])||9999)));grid.innerHTML=cars.length?cars.map(card).join(''):'<div class="empty-note">Nabídku vozidel připravujeme.</div>'}catch(e){grid.innerHTML='<div class="empty-note">Katalog se načítá.</div>'}}
loadCars();
